name: ğŸ›  Infrastructure Setup

on:
  workflow_dispatch:    # â† æ‰‹å‹•ãƒˆãƒªã‚¬ã®ã¿

permissions:
  id-token: write       # OIDC ã«ã‚ˆã‚‹ AssumeRole ç”¨
  contents: read        # ã‚³ãƒ¼ãƒ‰ checkout ç”¨

jobs:
  setup-infra:
    name: Setup Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.5'

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Run infra setup script
        env:
         AWS_PROFILE: ""
        run: bash scripts/setup_infra.sh
